<?php

namespace Warsztaty\FilterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AttributeValuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeValuesRepository extends EntityRepository
{
    /**
     * @param array $values
     * @return int
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function countItemsByValues(array $values)
    {
        $count = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('count(a.idValue) AS items')
            ->from('WarsztatyFilterBundle:AttributeValues', 'a')
            ->add('where', $this->getEntityManager()->getExpressionBuilder()->in('a.value', $values))
            ->getQuery()
            ->getSingleResult();

        return (int) $count['items'];
    }
}
