<?php

namespace Warsztaty\FilterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsCombinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsCombinationRepository extends EntityRepository
{
    public function getProductsByCombinationsParams(array $params)
    {
        // Helpers
        $relationMap = array();
        $attributeMap = $this->getEntityManager()
            ->getRepository('WarsztatyFilterBundle:Attributes')
            ->getAttributeMap();

        // Quick validation
        foreach (array('surface', 'technology', 'jons', 'warmfog', 'higro') as $key)
        {
            if (!array_key_exists($key, $params) OR !array_key_exists($key, $attributeMap)) {
                return false;
            }

            if ($params[$key])
            {
                foreach ($params[$key] as $id_value)
                {
                    $relation = $this->getEntityManager()
                        ->getRepository('WarsztatyFilterBundle:AttributeRelation')
                        ->findOneBy(array(
                            'idAttribute' => $attributeMap[$key],
                            'idValue' => $id_value
                    ));

                    if (!$relation) {
                        return false;
                    }

                    $relationMap['by_key'][$key][] = $relation->getIdRelation();
                    $relationMap['id_list'][] = $relation->getIdRelation();
                }
            }
        }

        if ($relationMap) {
            return $this->findByRelationIds($relationMap['id_list']);
        }

        return false;
    }

    /**
     * @param array $relation_ids
     * @return array
     */
    public function findByRelationIds(array $relation_ids)
    {
        $id_products = array();
        $getRelation = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('IDENTITY(p.idProduct) as idProduct')
            ->from('WarsztatyFilterBundle:ProductsCombination', 'p')
            ->add('where', $this->getEntityManager()->getExpressionBuilder()->in('p.idRelation', $relation_ids))
            ->getQuery()
            ->getArrayResult();

        /**
         * In the future create function to handle this
         * in elegant way.
         */
        if (!$getRelation) {
            $id_products = array('-1');
        }
        else
        {
            foreach ($getRelation as $relation) {
                $id_products[]  = $relation['idProduct'];
            }
        }

        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('WarsztatyFilterBundle:Products', 'p')
            ->add('where', $this->getEntityManager()->getExpressionBuilder()->in('p.id_product', $id_products))
            ->where('p.isAvailable = 1')
            ->getQuery()
            ->getArrayResult();
    }
}
